# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
---
version: 2.1
description: |
    Run load tests and reliability tests using DM.
    source_url: https://github.com/dmtest2/circleci.git

commands:
    login:
        description: |
            Login
        parameters:
            uid:
                default: ""
                description: Client UID to login to DM API
                type: string
            stress_id:
                default: ""
                description: Stress test ID
                type: string
        steps:
            #- run: mkdir -p workspace
            #- run: echo "Workspace directory has been created"
            - run:
                name: Login to API
                command: |
                    export ST_ID="<< parameters.stress_id >>"
                    echo "export ST_ID=\"$ST_ID\"" >> env.vars
                    resp=$(curl -sb -X POST https://api.dotcom-monitor.com/config_api_v1/LogIn?TypeUID=LogInAsLvWebApi \
                        --cookie-jar dm.auth -v \
                        -H "Content-Type: application/json" \
                        -d '{ "UID" : "<< parameters.uid >>" }')
                    if [[ $resp = "{\"Success\":true,\"Result\":\"OK\"}" ]]
                    then echo "client logged in"
                    else
                        echo "ERROR logging in"
                        exit 403
                    fi

            - persist_to_workspace:
                root: .
                paths:
                    - .

    get_stress:
        description: Get Stress test details
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Get Stress Test details
                command: |
                    source env.vars
                    curl -X GET https://api.dotcom-monitor.com/config_api_v1/StressTest/$ST_ID \
                        --cookie dm.auth \
                        -H "Content-Type: application/json"
                    echo "stress test $ST_ID getting details"
                    export duration=256
                    echo "export duration=$duration" >> env.vars
                    echo "111: $ST_ID --- $duration" 

    run_stress:
        description: Start Stress
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Run Stress Test
                command: |
                    source env.vars
                    echo "222: $ST_ID --- $duration" 
                    curl -X POST https://api.dotcom-monitor.com/config_api_v1/StressTest/$ST_ID/Run \
                        --cookie dm.auth \
                        -H "Content-Type: application/json" \
                        -d '{ "UserName": "user" }'
                    echo "stress test $ST_ID starting" 

jobs:
  build:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      #- checkout
      - run: echo "this is the build job"
  login_via_api:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      - login:
          uid: "99732cae08ae43b7a1d17f3564fdf135"
          #uid: "ee4b1545c7064b0f84c446e5a6e34832"
          stress_id: "131498"
      - run: echo "login done"
  get_st:
    docker:
      - image: cimg/base:current
    steps:
      - get_stress
  start:
    docker:
      - image: cimg/base:current
    steps:
      - run_stress

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - login_via_api:
          requires:
            - build
      - get_st:
          requires:
            - login_via_api
      - start:
          requires:
            - get_st