# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
---
version: 2.1
description: |
    Run load tests and reliability tests using DM.
    source_url: https://github.com/dmtest2/circleci.git

commands:
    test_login:
        description: |
            Login
        parameters:
            uid:
                default: ""
                description: |
                    Client UID to login to DM API
                type: string
        steps:
            - run: mkdir -p workspace
            - run: echo "Workspace directory has been created"
            - run:
                name: Login to API
                command: |
                    curl -X POST https://api.dotcom-monitor.com/config_api_v1/LogIn \
                        -H "Content-Type: application/json" \
                        -d '{ "UID" : "<< parameters.uid >>" }' \
                        --cookie-jar workspace/cookie/dm.auth -v
            - persist_to_workspace:
                root: workspace
                paths:
                    - cookie

    create_device:
        description: Create Device via API
        parameters:
            device_name:
                default: ""
                description: Device name
                type: string
        steps:
            - attach_workspace:
                at: /workspace
            - run:
                name: Create Device
                command: |
                    curl -X PUT https://api.dotcom-monitor.com/config_api_v1/devices \
                        -H "Content-Type: application/json" \
                        -d '{ "Locations": [1, 4], "Frequency": 10800, "Platform_Id": 1, "Name": "<< parameters.device_name >>" }' \
                        --cookie workspace/cookie/dm.auth 

jobs:
  build:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      #- checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      - test_login:
          uid: "ee4b1545c7064b0f84c446e5a6e34832"
      - run: echo "this is the test job"
  create:
    docker:
      - image: cimg/base:current
    steps:
      - create_device:
            device_name: "new device 14t"
      #- run: echo "device << parameters.device_name >> creation done"
      - run: echo "device creation done"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - create:
          requires:
            - test