# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
---
version: 2.1
description: |
    Run load tests and reliability tests using DM.
    source_url: https://github.com/dmtest2/circleci.git

commands:
    test_login:
        description: |
            Login
        parameters:
            uid:
                default: ""
                description: |
                    Client UID to login to DM API
                type: string
        steps:
            - run:
                name: Login to API
                command: |
                    curl -X POST https://api.dotcom-monitor.com/config_api_v1/LogIn \
                        -H "Content-Type: application/json" \
                        -d { "UID" : "<< parameters.uid >>" }
jobs:
  build:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      #- checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:current
    #resource_class: dmtest2/rc2
    steps:
      - test_login:
          uid: "ee4b1545c7064b0f84c446e5a6e34832"
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      #- build
      - test
      #- test:
      #    requires:
      #      - build